version: '3' # composeファイルのバーション指定
services:
  proxy: # service名
    container_name: Proxy
    build:  # ビルドに使用するDockerfileがあるディレクトリ指定
      context: ./.docker/Nginx/.
      dockerfile: Dockerfile
    volumes:
      - ./.docker/Nginx/conf/default.conf:/etc/nginx/conf.d/default.conf # マウントディレクトリ指定
      - ./.docker/Nginx/log/:/var/log/nginx # マウントディレクトリ指定
    networks:
      - private
    ports:
      - 18082:8080
    depends_on:
      - api
  api: # service名
    container_name: Go
    build:  # ビルドに使用するDockerfileがあるディレクトリ指定
      context: ./.docker/Go/.
      dockerfile: Dockerfile
    environment:
      APP_MODE: local
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: go_sample
      DB_NAME_TEST: go_sample_test
      DB_LOC: Asia%2FTokyo
    working_dir: "/go/src/work"
    command: air -c .air.toml # go run cmd/server/main.go
    stdin_open: true
    tty: true # コンテナの起動永続化
    volumes:
      - .:/go/src/work # マウントディレクトリ指定
    networks:
      - private
    ports:
      - 9020:9000
    depends_on:
      - "db"
  db: # service名
    container_name: MySql
    build:  # ビルドに使用するDockerfileがあるディレクトリ指定
      context: ./.docker/MySql/.
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: EPay_management
      MYSQL_PASSWORD: 3txWdCCbGYn
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db-data:/var/lib/mysql # マウントディレクトリ指定
    networks:
      - private
    ports:
      - 5432:3306

networks:
  private:
    driver: bridge

volumes:
  db-data:
    name: mysql-volume
    driver: local
